# Generated by Django 3.0 on 2019-12-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=5)),
                ('plot', models.CharField(max_length=1500)),
                ('imdb_rating', models.FloatField(default=0.0)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('watched', models.BooleanField(default=False)),
                ('trailer', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
    ]
