# Generated by Django 2.1.11 on 2019-12-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_superfan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestRevenueMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('revenue', models.IntegerField(max_length=50)),
            ],
        ),
    ]
