# Generated by Django 2.1.11 on 2019-12-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_superfan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie_title',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
