# Generated by Django 2.1.11 on 2019-12-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_superfan', '0002_highestrevenuemovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highestrevenuemovie',
            name='revenue',
            field=models.IntegerField(),
        ),
    ]
