# Generated by Django 2.1.11 on 2019-12-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_superfan', '0003_auto_20191212_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighestRevenueMovie',
        ),
    ]
